const VENDOR_DATA = [
   {
    id: 1,
    title: 'Flour',
    items: [
      {
        id: 1,
        name: 'Wheat',
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        qtyRequired: 25,
        vendorOne: 25,
        vendorTwo: 5,
        bakery: true,
        italian: true,
        indian: false,
      },
      {
        id: 2,
        name: 'Rice',
        imageUrl: 'https://i.ibb.co/ypkgK0X/blue-beanie.png',
        qtyRequired: 18,
        vendorOne: 18,
        vendorTwo: 8,
        bakery: true,
        italian: true,
        indian: false,
      },
      {
        id: 3,
        name: 'Grain',
        imageUrl: 'https://i.ibb.co/QdJwgmp/brown-cowboy.png',
        qtyRequired: 35,
        vendorOne: 35,
        vendorTwo: 5,
        bakery: true,
        italian: true,
        indian: false,
      },
    ]
  },
   {
    id: 2,
    title: 'Fats',
    items: [
      {
        id: 10,
        name: 'Butter',
        imageUrl: 'https://i.ibb.co/0s3pdnc/adidas-nmd.png',
        qtyRequired: 220,
        vendorOne: 10,
        vendorTwo: 4,
        backery: false,
        indian: true,
        italian: false,
      },
      {
        id: 11,
        name: 'Olive',
        imageUrl: 'https://i.ibb.co/dJbG1cT/yeezy.png',
        qtyRequired: 280,
        vendorOne: 10,
        vendorTwo: 4,
        backery: false,
        indian: true,
        italian: false,
      },
      {
        id: 12,
        name: 'Mustard',
        imageUrl: 'https://i.ibb.co/bPmVXyP/black-converse.png',
        qtyRequired: 110,
        vendorOne: 10,
        vendorTwo: 4,
        backery: false,
        indian: true,
        italian: false,
      },
    ]
  },
 {
    id: 3,
    title: 'Vegetables',
    items: [
      {
        id: 18,
        name: 'Mushroom',
        imageUrl: 'https://i.ibb.co/XzcwL5s/black-shearling.png',
        qtyRequired: 125,
        vendorOne: 10,
        vendorTwo: 4,
        backery: false,
        indian: true,
        italian: false,
      },
      {
        id: 19,
        name: 'Corn',
        imageUrl: 'https://i.ibb.co/mJS6vz0/blue-jean-jacket.png',
        qtyRequired: 90,
        vendorOne: 90,
        vendorTwo: 0,
        bakery: true,
        italian: true,
        indian: false,
      },
      {
        id: 20,
        name: 'Grey Jean Jacket',
        imageUrl: 'https://i.ibb.co/N71k1ML/grey-jean-jacket.png',
        qtyRequired: 90,
        vendorOne: 90,
        vendorTwo: 0,
        bakery: true,
        italian: true,
        indian: false,
      },
      {
        id: 21,
        name: 'Onions',
        imageUrl: 'https://i.ibb.co/s96FpdP/brown-shearling.png',
        qtyRequired: 165,
        vendorOne: 10,
        vendorTwo: 4,
        backery: false,
        indian: true,
        italian: false,
      },
      {
        id: 22,
        name: 'Capsisum',
        imageUrl: 'https://i.ibb.co/M6hHc3F/brown-trench.png',
        qtyRequired: 185,
        vendorOne: 10,
        vendorTwo: 4,
        backery: false,
        indian: true,
        italian: false,
      }
    ]
  },
{
    id: 4,
    title: 'Add-Ons',
    items: [
      {
        id: 23,
        name: 'Salt',
        imageUrl: 'https://i.ibb.co/7CQVJNm/blue-tank.png',
        qtyRequired: 25,
        vendorOne: 25,
        vendorTwo: 5,
        bakery: true,
        italian: true,
        indian: false,
      },
      {
        id: 24,
        name: 'Sugar',
        imageUrl: 'https://i.ibb.co/4W2DGKm/floral-blouse.png',
        qtyRequired: 20,
        vendorOne: 20,
        vendorTwo: 0,
        bakery: true,
        italian: true,
        indian: false,
      },
      {
        id: 25,
        name: 'Vanilla',
        imageUrl: 'https://i.ibb.co/KV18Ysr/floral-skirt.png',
        qtyRequired: 80,
        vendorOne: 80,
        vendorTwo: 0,
        bakery: true,
        italian: true,
        indian: false,
      },
      {
        id: 26,
        name: 'Olive',
        imageUrl: 'https://i.ibb.co/N3BN1bh/red-polka-dot-dress.png',
        qtyRequired: 80,
        vendorOne: 80,
        vendorTwo: 0,
        bakery: true,
        italian: true,
        indian: false,
      },
    ]
  },
];

export default VENDOR_DATA;