const DataActionTypes = {
  FETCH_COLLECTIONS_START_CHEF: 'FETCH_COLLECTIONS_START_CHEF',
  FETCH_COLLECTIONS_SUCCESS_CHEF: 'FETCH_COLLECTIONS_SUCCESS',
  FETCH_COLLECTIONS_FAILURE_CHEF: 'FETCH_COLLECTIONS_FAILURE_CHEF'
};

export default DataActionTypes;
